# CSC-321: Data Mining and Machine Learning
# Manav Bilakhia


## Assignment 1: Oh, the data structures we shall know

First, don't forget to make a copy (File -> Save copy in drive), otherwise you wont be able to edit. **Then** don't forget to add your name, by double clicking the text cell.

In this notebook, I'm going to quickly take you through some techniques in python, and some data structures, from lists and dictionaries to arrays and dataframes.

Get ready, because you're going to have to do some reading.

Given the nature of this class, there's **no way** we have time to cover all the important data structures, so you'll have to do some self learning. That's ok, you're all computer scientists (even if it isn't your primary focus), so I can trust you to go about this the right way.

I'll provide links to tutorials and documentation. It's good practice to read through them and try things out for yourself.

Two other notes: In this class, for the most part, I'm **not** going to grade the quality of your code. This assignment is different - I mandate **how** to do some things. But in general I'm not here to grade your code, beyond "does it get the job done." I want you to grasp the concepts. 

Second, I don't mind if you use resources like stack overflow. Learning to use those resources is also important. I never exactly remember the syntax for a dictionary comprehension with if statements, and so I look it up. It's ok to do the same.

It is **not** ok to copy complete homework solutions from the iternet (this includes ChatGPT and similar systems), **or** to copy from each other. Each homework assignment, this one included, has a text box with the Union College Honor Code included. You will add your initials at the end of the statement for **every** homework. 

If in any doubt - **ask me about it**.

### Part 1: Functions with multiple return values

Read the tutorial at: https://www.tutorialspoint.com/How-do-we-return-multiple-values-in-Python

(a) Write a function called minmax, that takes a list as a single argument, and returns two values as a tuple - the minimum value in the list, and the maximum value in a list. 

(b) Use the [random.randint(a,b)](https://www.w3schools.com/python/ref_random_randint.asp) function to create a list filled with 100 random integers in the range 0 to 1000 (inclusive).

(c) Pass this list to your function from (a), capture the two return values into TWO distinct variables, and print them nicely! (i.e. Print two, distinct, meaningful output messages, not just the tuple returned).

In [4]:
import random

def minmax(lst):
    return min(lst), max(lst)

rand_lst = [random.randint(0, 1000) for _ in range(100)]
min_val, max_val = minmax(rand_lst)

print("minval:", min_val)
print("maxval:", max_val)

minval: 5
maxval: 990



### Part 2: Lists and list comprehension

Lists are a major part of all programming languages (except for the ones where they're not). List comprehensions are a particularly python-ish way of creating and manipulating lists. 

I want you to complete the tasks (a) through (g) below **using** list comprehension. Yes, you can achieve them by **not** using comprehension - but where's the fun in that, and I'll penalize you for not using list comprehension.

First, read the tutorial at: https://www.programiz.com/python-programming/list-comprehension


(a) You *could* have solved part1(b) above using a list comprehension. If you did, great. If you didn't, great. Either way do 1(b) (and 1(c)) **again** below, generating your list of random numbers using list comprehension. Print the min and the max values in the lsit.

For (b) through (e) take the list called startList, below, and use list comprehension to complete the following. You must use list comprehension, and you must start with the original list (startList) each time. You must print the resulting list at the end each time.

(b) Create a new list from every other element, starting at index 0. The range function can help you here.

(c) Create a new list that contains True for each element in the original list that is even, False if it is odd. Note, those are BOOLEAN values, not strings

(d) Create a new list that replaces the values in the original list with 1, 2 or 3 under the following conditions. If the value is less than 3, make the new value 1, if it's greater than or equal to 3. but below 6, make it equal to 2, otherwise make it 3

(e) Go through the list and multiply each elements by 5, putting the result in a new list.

The following two parts use the variable data, instead of startList. Both are east to do if you remember how **slicing** and **indexing** work.

(f) Go through the list of lists contained in the variable data defined below, and extract all elements from each list **except** the last one, and put into a new list of lists. 

e.g. the output should be: [[1, 2], [4, 5], [7, 8], [10, 11]]

(g) Go through the list of lists contained in the variable data, and create a single list containing ONLY the last element of each nested list. You must use list comprehension.

e.g. the output should be: [3, 6, 9, 12]

In [5]:


# Use this list for b-e above
startList = [2, 7, 1, 9, 1, 4, 8, 10, 2, 3, 5]
new_list = [startList[i] for i in range(0, len(startList), 2)]
print("b:", new_list)

new_list = [True if i % 2 == 0 else False for i in startList]
print("c:", new_list)

new_list = [1 if i < 3 else 2 if i < 6 else 3 for i in startList]
print("d:", new_list)

new_list = [i * 5 for i in startList]
print("e:", new_list) 


# Use this list for g-g above
data = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
new_list = [[j for j in lst[:-1]] for lst in data]
print("f:", new_list)

new_list = [lst[-1] for lst in data]
print("g:", new_list)

b: [2, 1, 1, 8, 2, 5]
c: [True, False, False, False, False, True, True, True, True, False, False]
d: [1, 3, 1, 3, 1, 2, 3, 3, 1, 2, 2]
e: [10, 35, 5, 45, 5, 20, 40, 50, 10, 15, 25]
f: [[1, 2], [4, 5], [7, 8], [10, 11]]
g: [3, 6, 9, 12]

### Part 3: Dictionaries, and dictionary comprehension 

Just as with lists, you can use dictionary comprehension to create dictionaries. 

Read the tutorial at: https://www.programiz.com/python-programming/dictionary-comprehension


(a) Take the two lists below. The first is a list of words. The second is a list of counts of those words. So for example, the word animal occurs 12 times in some test. Use dictionary comprehension to create a dictionary of counts, where the key is the name, and the value is the count of that thing, Print the resulting dictionary.

(b) Now use dictionary comprehension to create a dictionary of counts, but **only** of words that start with a vowel (a, e, i, o or u). Print the resulting dictionary.

In [6]:
words = ['animal','insect','dinosaur','fish','plant','shrub','tree','arachnid','iguana']
counts = [12,432,7,800,2000,1,14,7,6]
vowels = ['a', 'e', 'i', 'o', 'u']

count_dict = {words[i]: counts[i] for i in range(len(words))}
print("a:", count_dict)

vowel_dict = {words[i]: counts[i] for i in range(len(words)) if words[i][0] in vowels}
print("b:", vowel_dict)

a: {'animal': 12, 'insect': 432, 'dinosaur': 7, 'fish': 800, 'plant': 2000, 'shrub': 1, 'tree': 14, 'arachnid': 7, 'iguana': 6}
b: {'animal': 12, 'insect': 432, 'arachnid': 7, 'iguana': 6}

### Part 4: Numpy

Next up - n-dimensional arrays. Numpy is a library that brings n-dimensional arrays to python. Arrays are powerful, because it allows us to simplify operations over data, for instance you'll see that part2(e) can be done much more easily with arrays. However, you need to read the documentation first. Here is the key link:

https://numpy.org/devdocs/user/quickstart.html

You're **really** interested in:
- creating arrays
- reshaping arrays
- built in attributes of arrays
- array operations
- indexing and slicing arrays

Then work on the following:

(a) convert the startList to a one dimensional array. Print this array, and it's shape.

(b) **multiply** every value of the array from (a) by 5. The result should be another one dimensional array. 

(c) convert the startList into a two dimensional array, of 5 rows of 4 columns. Print this array, and print it's shape. Nicely.

Remember in class I talked about Machine Learning as a process that uses some features (think of things like size and mass) to predict a class (like the type of coin)? 

Well, it turns out that the library we're going to use (scikit learn) **expects** this data in the form of arrays. It expects the data values for each instance to be a row in an n-dimensional array (so example (c) above could be 5 instances of data). 

It **also** expects the data set to be **split** into **two** parts. One of them is all the input features, and the second is the class - the thing we're predicting. This will look like the solutions to 2(f) (the input values) and 2(g) (the values we're predicting).

For now, we'll imagine that the last feature of each instance is the value we're trying to predict. Therefore:

(d) use array slicing on (c) above to produce similar output to 2(f) and 2(g) above. One variable should contain 5 rows of 3 columns (all the data **except** the last column from each row), and one variable that is a 5 by 1 array, containing the values from the last column.

In [7]:
import numpy as np

startList = [2,4,6,8,1,3,5,9,22,44,66,88,11,33,55,99,222,444,666,888]
arr = np.array(startList)

print("a:", arr)
print("a:", arr.shape)

arr *= 5
print("b:", arr)

arr = np.array(startList).reshape(5, 4)

print("c:", arr)
print("c:", arr.shape)

X = arr[:, :-1]
y = arr[:, -1]
print(X)
print(y)

a: [  2   4   6   8   1   3   5   9  22  44  66  88  11  33  55  99 222 444
 666 888]
a: (20,)
b: [  10   20   30   40    5   15   25   45  110  220  330  440   55  165
  275  495 1110 2220 3330 4440]
c: [[  2   4   6   8]
 [  1   3   5   9]
 [ 22  44  66  88]
 [ 11  33  55  99]
 [222 444 666 888]]
c: (5, 4)
[[  2   4   6]
 [  1   3   5]
 [ 22  44  66]
 [ 11  33  55]
 [222 444 666]]
[  8   9  88  99 888]

### Part 5: Pandas

Ok, that was a lot of build up to this: an introduction to Pandas. [Pandas](https://www.youtube.com/watch?v=ySRMDsJoIzM&ab_channel=TricksyPets) are cute bears, that everyone loves. Pandas is **also** the most widely used library for data science in Python. I can't introduce you to **all** of pandas, but I can get you to think about what pandas does from a computer science perspective.

If you've ever worked with the language R, then you already know about the dataframe. Pandas brings the R dataframe and all the associated methods to Python. 

You can think of the dataframe as like a spreadsheet - with rows and columns. Look back at Assignment 0, where I use Pandas at the bottom to load a data set. 

Because we're computer scientists, it also helps to think of dataframes in terms of other data structures.

Each **column** in a pandas dataframe is a Series. And a Series is effectively a cross between a dictionary, and an n-dimensional array. Hey! That's why they had us do dictionaries and arrays.

A dataframe is just a collection of series. 

There's an introduction to Pandas [you can read](https://www.learndatasci.com/tutorials/python-pandas-tutorial-complete-introduction-for-beginners/). There's more here than you need for this assignment, but I absolutely recommend getting familiar with pandas.

Below I load the wine data I used in Assignment 0 using the csv at my github account using pandas, exactly as I did in Assignment 0. I set the attributes - the column headings - as I read in the data. For now, they aren't very meaningful. 

I then show the head - the first 5 rows of the data.

Pandas is an incredibly powerful library, but for now, see if you can:

(a) Print the number of rows and columns in the wine data (HINT: Shape can help you here)

(b) Print **just** the values from the att3 column. (HINT: Datframes behave like dictionaries in many ways)

(c) Print the mean values for each column (and only the mean values) (HINT: Dataframes have methods that work over them)

(d) Tell me if there are any **missing** values in this data. Missing values are represented by the special value NaN (which comes from numpy, Not a Number). (HINT: Some methods can be combined, such as summing all the NaN values, to get a count on a column by column basis)

(e) We can use pandas to prepare data for machine learning. Just as with 4(d) above, we want to create **two** variables. **One** will be all the features **except** the class. The other will contain **just** the class values.

To do this with pandas is easy. 

There is a method called drop, which allows you to drop a column. Let's say that att8 is the column we will try to predict.

So, our input features will be everything except the column att8. The class values will be **only** the values in the column called att8.

Create two variables, called X for the input features, and y for the class values. Their structure (the shape of the data) should be (rows, 11) for the X data, and ( , rows) for the y data, where rows is the number of instances in the data.

In [8]:
import pandas as pd

# Assign column names
labels = ['att0','att1','att2','att3','att4','att5','att6','att7','att8','att9','att10','att11']

# Load the data
wine_data = pd.read_csv("https://raw.githubusercontent.com/nixwebb/CSV_Data/master/winequality-white.csv",names=labels)

# Show the head of the data
wine_data.head()

,att0,att1,att2,att3,att4,att5,att6,att7,att8,att9,att10,att11
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [18]:
# Write your solutions (a) through (e) here
print("a:", wine_data.shape)

print("b:", wine_data['att3']) 

print("c:",wine_data.mean())

print("d:", wine_data.isnull().sum()) # no uesn as the sum in each column is 0

X = wine_data.drop('att8', axis=1)  # axis=1 specifies that we are dropping a column, not a row
y = wine_data['att8']
X = X.to_numpy().reshape((4898, 11))
y = y.to_numpy().reshape((4898, 1))
print("e:", X)
print("e:", y)

a: (4898, 12)
b: 0       20.7
1        1.6
2        6.9
3        8.5
4        8.5
        ...
4893     1.6
4894     8.0
4895     1.2
4896     1.1
4897     0.8
Name: att3, Length: 4898, dtype: float64
c: att0       6.854788
att1       0.278241
att2       0.334192
att3       6.391415
att4       0.045772
att5      35.308085
att6     138.360657
att7       0.994027
att8       3.188267
att9       0.489847
att10     10.514267
att11      5.877909
dtype: float64
d: att0     0
att1     0
att2     0
att3     0
att4     0
att5     0
att6     0
att7     0
att8     0
att9     0
att10    0
att11    0
dtype: int64
e: [[ 7.    0.27  0.36 ...  0.45  8.8   6.  ]
 [ 6.3   0.3   0.34 ...  0.49  9.5   6.  ]
 [ 8.1   0.28  0.4  ...  0.44 10.1   6.  ]
 ...
 [ 6.5   0.24  0.19 ...  0.46  9.4   6.  ]
 [ 5.5   0.29  0.3  ...  0.38 12.8   7.  ]
 [ 6.    0.21  0.38 ...  0.32 11.8   6.  ]]
e: [[3.  ]
 [3.3 ]
 [3.26]
 ...
 [2.99]
 [3.34]
 [3.26]]

## Honor Code Affirmation ##

As a student at Union College, I am part of a community that values intellectual effort, curiosity and discovery. I understand that in order to truly claim my educational and academic achievements, I am obligated to act with academic integrity. Therefore, I affirm that I will carry out my academic endeavors with full academic honesty, and I rely on my fellow students to do the same.

MB